/****** Object:  Table [dbo].[Category] ******/
CREATE TABLE [dbo].[Category](
	[CategoryID]	 [SMALLINT] PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Category]	 [NVARCHAR](60) NULL,
	[Name]			 [VARCHAR](40) NULL,
	[ParentID]		 [SMALLINT] NULL,	
	[IsShownInMenu]	 [BIT] DEFAULT 0 NULL,
	[RecStatus]		 [CHAR](1) DEFAULT 'A'
)
Go
--Dec 2023 Data
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அகராதி / களஞ்சியம்','Dictionary / Encyclopedia',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அதிரடி & சாகசம்','Action & Adventure',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அரசியல்','Politics',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அறவியல்','Ethics',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அறிவியல், தொழில்நுட்பம் மற்றும் மருத்துவம்','Sciences, Technology & Medicine',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஆட்சியியல்','Civilian',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இதழ் தொகுப்பு','Magazine Gallery',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இயற்கை - சுற்றுச்சூழல்','Nature',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இலக்கணம்','Grammar',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இலக்கியம்','Literature & Fiction',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இல்லறம்','NULL',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'உடல் நலம் & குடும்பம்','Health, Family & Personal Development',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கட்டுரைகள்','Essays',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கணினி, இணையதளம் மற்றும் டிஜிட்டல் மீடியா','Computer, Internet & Digital Media',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கலை & திரைப்படம்','Arts, Film & Photography',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கவிதைகள்','Poems',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'காதல்','Romance',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குழந்தைகள் மற்றும் சிறுவர்/சிறார்','Children''s & Young Adult',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குறிப்பு','Reference',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கைவினைகள், வீடு & வாழ்க்கை','Crafts, Home & Lifestyle',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சங்க இலக்கியம்','Sangam literature',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சட்டம்','Law',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமூகம் & சமூக அறிவியல்','Society & Social Sciences',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சுயசரிதைகள் மற்றும் உண்மை கதை','Biographies & True story',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சுயமுன்னேற்றம் / தன்னம்பிக்கை','Self-Improvement / Self-Confidence',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சொற்பொழிவுகள்','Lectures',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தத்துவம்','NULL',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தொல்லியல்','Archeology',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தேர்வு தயாரிப்பு & பாடப்புத்தகங்கள்','Exam Preparation & Textbooks',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நகைச்சுவை','Humour',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நேர்காணல் & உரையாடல்கள்','Interview & Conversations',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பகுத்தறிவு','Rational',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பயணம்','Travel',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பழமொழிகள்','NULL',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பாடப்புத்தகங்கள்','TextBooks',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'புதினம்(நாவல்)','Novel',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பொது அறிவு','General Knowledge',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பொன்மொழி','NULL',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மதம்','Religion',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மருத்துவம்','NULL',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழி, மொழியியல் மற்றும் எழுதுதல்','Language, Linguistics & Writing',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வட்டார நூல்கள் / நாட்டுப்புறவியல்','Regional texts / Folklore',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வணிக மற்றும் பொருளியல்','Business & Economics',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வரலாறு','History',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'விடுகதை','NULL',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'விளையாட்டு','Sports',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வேளாண்மை மற்றும் விவசாயம்','Agriculture & Farming',NULL,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அகராதி / களஞ்சியம்','Dictionary / Encyclopedia',1,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அதிரடி & சாகசம்','Action & Adventure',2,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அம்பேத்கரியம்','NULL',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அரசியல் சித்தாந்தங்கள்','Political Ideologies',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அரசு','Government',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இந்துத்துவா ','Hindutva',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இஸ்லாமியம் ','Islam',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஈழம் / தமிழீழம்','Eelam / Tamil Eelam',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கட்டுரைகள்','Essays',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கம்யூனிசம் / பொதுவுடைமை','Communism',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கிறித்துவம்','',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமூக நீதி','Social Justice',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சர்வதேச உறவுகள் மற்றும் உலகமயமாக்கல்','International Relations & Globalization',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சுதந்திரம் & பாதுகாப்பு','Freedom & Security',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தமிழினம் / தமிழ்த் தேசியம்','Tamil Nationality',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தலித்தியம்','Dhalithiyam',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'திராவிடம் / திராவிடர்','Dravidian',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பிராமணியம்','',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பெரியாரியம்','NULL',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பொது நிர்வாகம்','Public Administration',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மார்க்சியம்','NULL',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',3,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அறவியல்','Ethics',4,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இயற்பியல்','Physics',5,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'உயிரியல்','Biology',5,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கணிதம்','Mathematics',5,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சுற்றுச்சூழல்','Environment',5,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நிலவியல்','Geography',5,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'புவி அறிவியல்','Earth Sciences',5,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பொறியியல் மற்றும் தொழில்நுட்பம்','Engineering & Technology',5,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'போக்குவரத்து மற்றும் தானியங்கி','Transportation & Automotive',5,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மருத்துவம்','Medicine',5,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வானியல்','Astronomy',5,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வேதியியல்','Chemistry',5,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',5,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஆட்சியியல்','Civilian',6,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நிர்வாகம்','',6,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இதழ் / இதழ் தொகுப்பு','Magazine Collection',7,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சிறார் இதழ்','Children''s Magazine',7,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வார / மாத இதழ்கள்','Weekly / Monthly Magazines',7,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இயற்கை','Nature',8,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கட்டுரைகள்','Essays',8,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சுற்றுச்சூழல் / சூழலியல்','Environment',8,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பறவைகள் / பூச்சிகள் / விலங்குகள்','Birds',8,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',8,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இலக்கணம்','Grammar',9,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அந்தாதி','NULL',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அனுபவம்','Experience',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஆய்வு கட்டுரைகள்','Research Essays',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இசுலாமிய இலக்கியம்','Islamic Literature',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இதிகாசங்கள்','Epics',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இந்திய இலக்கியம்','Indian Literature',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இயல்-இசை-நாடகம்','Prose, Music and Drama',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இலக்கியக் கோட்பாடு, வரலாறு மற்றும் விமர்சனங்கள்','Literary Theory, History & Criticism',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இலக்கியம்','Literature',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இலக்கியம் மற்றும் கற்பனை','NULL',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'உரை','',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'உரைநடை நாடகம்','Prose play',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'உலா','NULL',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கடித இலக்கியம்','NULL',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கட்டுக்கதைகள், புனைவுகள் & திரைப்படங்கள்','Myths, Legends & Sagas',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கலம்பகம்','NULL',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'காப்பிய இலக்கியம்(காப்பியங்கள்)','Epics',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கிளாசிக் கற்பனை/புனைகதை','Classic Fiction',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கிறித்துவ இலக்கியம்','Christian Literature',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குறவஞ்சி','NULL',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கோவை','NULL',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமகால அறிவியல்','Contemporary Fiction',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமண இலக்கியம்','Jain literature',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமய  இலக்கியம்','Religious Literature',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சித்தர் பாடல்கள்','Siddhar songs',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சைவ இலக்கியம்','Saiva Literature',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தல புராணங்கள்','Thala Puranagal',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'திரட்டு நூல்கள்','',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தூது','NULL',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தொகை நூல்கள்','Anthologies',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நவீன இலக்கியம்','Modern Literature',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நாடகம் / நாடகங்கள்','Drama / Play',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பரணி','NULL',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பள்ளு','NULL',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பாடல்கள்','Songs',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பிள்ளைத் தமிழ்','NULL',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'புராணங்கள்','Myths',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வைணவ இலக்கியம்','Vaishnava Literature',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',10,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அந்தரங்கம்','NULL',11,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இல்லறம்','NULL',11,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கருத்தரிப்பு','NULL',11,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பாலியல்','NULL',11,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மகப்பேறு','NULL',11,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அனுபவம்','Experience',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஆசனங்கள்','NULL',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஆரோக்கியம் & ஆரோக்கியமான வாழ்க்கை','Healthy Living & Wellness',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'உடற்பயிற்சி','Exercise',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'உடல் நலம்','Health',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குடும்பம் & உறவுகள்','Family & Relationships',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தனிப்பட்ட வளர்ச்சி மற்றும் சுய உதவி','Personal Development & Self-Help',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தியானம்','NULL',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'திருமணம் மற்றும் இல்லறம்','Marriage and family life',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பிராணாயாமம்','NULL',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மனம், உடல் மற்றும் ஆத்மா','Mind, Body & Spirit',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மூச்சுக் கலை','NULL',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'யோகாசனம்','NULL',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Transalatoin',12,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அம்பேத்கரியம்','NULL',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அரசியல்','Politics',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அறிவியல்','Science',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அனுபவம்','Experience',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஆத்திகம்','Theism',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஆய்வு கட்டுரைகள்','Research Articles',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஆன்மிகம்','Spirituality',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இந்துத்துவம்','Hinduism',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இலக்கியம்','Literature',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'உடல்நலம்-மருத்துவம்','Health-Medicine',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'உளவியல்','Psychology',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கட்டுரைகள்','Essays',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கம்யூனிசம்','NULL',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கலாச்சாரம், பண்பாடு','Culture',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கள ஆய்வு','NULL',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குடும்பம் / உறவு','NULL',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குழந்தை வளர்ப்பு','Child Care',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமூக நீதி','Social justice',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமையல்-உணவு','Kitchen Food',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சாதி','NULL',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சாதி - தீண்டாமை','NULL',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சாதி ஒழிப்பு','NULL',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சிந்தனை','',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தன்னம்பிக்கை ','Self-confidence',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'திரைப்படம்','NULL',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தொல்லியல்','Archaeology',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நகைச்சுவை','Joke',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நாத்திகம்','Atheism',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பாலியல்','NULL',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பிராமணியம்','Brahmanism',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பெண்ணியம் / பெண்ணுரிமை','Feminism',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பெரியாரியம்','NULL',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மதம்','Religion',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மார்க்சியம்','Marxism',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மானுடவியல்','Anthropology',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'விமர்சனம் / விமர்சனங்கள்','NULL',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இணைய மற்றும் வலை','Internet & Web',14,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இயங்குதளங்கள்','Operating Systems',14,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கணினி & வீடியோ கேம்கள்','Computer & Video Games',14,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கணினி அறிவியல்','Computer Science',14,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கணினி பாதுகாப்பு','Computer Security',14,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'டிஜிட்டல் மீடியா மற்றும் கிராபிக் டிசைன்','Digital Media & Graphic Design',14,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தரவுத்தளங்கள்','Databases',14,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நிரலாக்க மற்றும் மென்பொருள் விருத்தி','Programming & Software Development',14,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நெட்வொர்க்ஸ் மற்றும் கணினி மேலாண்மை','Networks & System Administration',14,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மென்பொருள் மற்றும் வணிக பயன்பாடுகள்','Software & Business Applications',14,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வன்பொருள் மற்றும் கையடக்க சாதனங்கள்','Hardware & Handheld Devices',14,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',14,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அருங்காட்சியகங்கள் & அரும் பொருட்காட்சி மனையை நிர்வகித்தல்','Museums & Museology',15,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இசை','Music',15,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஓவியம் / ஓவியர்கள்','Drawing / Painting',15,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கட்டிடக்கலை','Architecture',15,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கட்டுரைகள்','Essays',15,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சினிமா & ஒளிபரப்பு','Cinema & Broadcast',15,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'திரைக்கதை-வசனம்','Screenplay',15,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'திரைப்படம்','Cinema',15,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நடனம்','Dance',15,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'புகைப்படம் எடுத்தல்','Photography',15,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வடிவமைப்பு மற்றும் ஃபேஷன்','Design & Fashion',15,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வரலாறு, தியரி மற்றும் விமர்சனங்கள்','History, Theory & Criticism',15,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',15,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கவிதைகள்','Poems',16,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சங்க இலக்கியம்','Sanga Literature',16,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பிள்ளைத் தமிழ்','',16,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஹைக்கூ','Haiku',16,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',16,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'காதல்','Romance',17,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மற்றவை','Other',17,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',17,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அறிவியல், இயற்கை மற்றும் தொழில்நுட்பம்','Science, Nature & Technology',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஆரம்ப கற்றல்','Early Learning',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இரகசியங்கள் மற்றும் உந்துதல்கள்','Mysteries & Curiosities',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இலக்கியம் மற்றும் கற்பனை','Literature & Fiction',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஊடாடும் &  நடவடிக்கை புத்தகங்கள்','Interactive & Activity Books',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஓவியம், கலை மற்றும் இசை','Painting, Arts & Music',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'காமிக்ஸ் / கிராஃபிக் நாவல்','Comics / Graphic Novel',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குடும்பம், தனிப்பட்ட மற்றும் சமூக சிக்கல்கள்','Family, Personal & Social Issues',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குறிப்பு','Reference',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குற்றம் & திகில்','Crime & Thriller',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கைவினைகள்','Crafts, Hobbies & Practical Interests',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சாதனை','Adventure',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சிறார் பாடல்கள்','NULL',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சிறுவர் கதைகள்','NULL',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சிறுவர் நாவல்கள்','NULL',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நகைச்சுவை','Humour',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'படக்கதைகள்','Comics',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'படப்புத்தகங்கள் & குழந்தைகள் மற்றும் சிறுவர்/சிறார் நூல்கள்','Picture Books',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சிறார் கட்டுரைகள்','Money & Jobs',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பாரம்பரிய கதைகள்','Traditional Stories',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பேண்டஸி, நவீன அறிவியல் மற்றும் திகில்','Fantasy, Science Fiction & Horror',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மதம்','Religion',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழி கற்றல்','Language Learning',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வரலாறு','History',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வரலாற்று கற்பனை','Historical Fiction',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'விளையாட்டு','Sport',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'விளையாட்டு, விளையாட்டு பொம்மைகள்','Games, Toys & Activities',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',18,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குறிப்பு','Reference',19,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அழகு குறிப்புகள்','Beauty Tips',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இல்லம் மற்றும் ஹவுஸ் பராமரிப்பு','Home & House Maintenance',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'உணவு முறை','Diet',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'உணவு, பானம் மற்றும் பொழுதுபோக்கு','Food, Drink & Entertaining',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கைவினைப் பொருட்கள், அலங்கார கலைகள் & கைத்தொழில்','Handicrafts, Decorative Arts & Crafts',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமையல்','Cooking',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'செல்லப்பிராணிகள்','Pets',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தியானம் / ஞானம்','Meditation / Enlightenment',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தோட்டம்','Gardening',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தையற்கலை','Tailoring',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மாதிரிகள் மற்றும் மாடல்','Models & Model Railroading',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வாழ்க்கைமுறை மற்றும் தனிப்பட்ட உடை வழிகாட்டிகள்','Lifestyle & Personal Style Guides',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'விளையாட்டு மற்றும் வினாவிடை','Games & Quizzes',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',20,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இதிகாசம்','Mythology',21,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஐஞ்சிறுகாப்பியம்','Aincirukappiyam',21,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஐம்பெருங்காப்பியம்','Aimperunkappiyam',21,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சங்க காலக் கவிதைகள்','Sangam Poets',21,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சிற்றிலக்கியம்','Cirrilakkiyam',21,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தமிழ்க் காப்பியம்','NULL',21,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நீதி நூல்கள்','Justice books',21,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பக்தி இலக்கியம்','Devotional Literature',21,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பதினெண் கீழ்க்கணக்கு','Seventeen below',21,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பதினெண் மேற்கணக்கு','Eighteen West',21,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மற்றவை','Others',21,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சட்டம்','Law',22,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஆராய்ச்சி கட்டுரை','Research Essays',23,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'உளவியல்','Psychology',23,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கல்வி','Education',23,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமூக நலத்துறை மற்றும் சமூக சேவைகள்','Social Welfare & Social Services',23,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமூகம் & வளர்ப்பு','Society & Culture',23,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமூகவியல்','Sociology',23,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தத்துவம்','Philosophy',23,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மானிடவியல்','Anthropology',23,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Transalatoin',23,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அனுபவம்','',24,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'உண்மை கணக்குகள்','',24,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கடிதங்கள் மற்றும் பதிவேடுகள்','',24,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சுயசரிதைகள் / வாழ்க்கை வரலாறு மற்றும் தன் வரலாறு','',24,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',24,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சுயமுன்னேற்றம் / தன்னம்பிக்கை','',25,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',25,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சொற்பொழிவுகள் / உரைகள்','Speech',26,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',26,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இந்தியத் தத்துவம்','NULL',27,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கீழைத் தத்துவம்','NULL',27,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தத்துவம்','NULL',27,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தமிழர் தத்துவம்','NULL',27,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மார்க்சியத் தத்துவம்','NULL',27,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மேலை நாட்டுத் தத்துவம்','NULL',27,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',27,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தொல்லியல் / கல்வெட்டு','',28,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மற்றவை','',28,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அரசு தேர்வுகள்','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இக்னோ நுழைவு தேர்வு','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஒருங்கிணைந்த மேலாண்மை நுழைவு','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சட்டம் நுழைவுத் தேர்வுகள்','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சர்வதேச நுழைவுத் தேர்வுகள்','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தொழில்முறை சான்றிதழ் தேர்வுகள்','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நிதி மற்றும் கணக்கியல்','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பாதுகாப்பு','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பாலிடெக்னிக்குகள் மற்றும் ஐடிஐ தேர்வுகள்','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பொறியியல் நுழைவுத் தேர்வுகள்','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பேட்டி தயாரிப்பு','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'போட்டித் தேர்வுகள்','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மருத்துவ நுழைவுத் தேர்வுகள்','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மற்றவை','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'யுபிஎஸ்சி தேர்வுகள்','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வங்கி மற்றும் காப்புறுதி','',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',29,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நகைச்சுவை','Comedy',30,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கேள்வி-பதில்','Question & Answer',31,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நேர்காணல் & உரையாடல்கள்','Interview',31,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பேட்டிகள்','Interviews',31,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பகுத்தறிவு','Rational',32,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',32,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சுற்றுலா & விடுமுறை வழிகாட்டிகள்','',33,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பயண கட்டுரை / பயண அனுபவம்','',33,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',33,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பழமொழிகள்','',34,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அறிவியல் மற்றும் கணிதம்','Science & Maths',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஆங்கிலம்','English',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கணினி அறிவியல்','Computer',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சட்டம்','Law',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமூக அறிவியல்','Social Science',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தமிழ் ','Tamil',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தொடர்பாடல் மற்றும் இதழியல்','',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பள்ளி உரைகள்','',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பொறியியல்','Engineering',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'போதனை மற்றும் கல்வி','',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மருத்துவம் மற்றும் சுகாதார அறிவியல்','',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மனிதநேயம்','',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வரலாறு ','History',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வர்த்தக மற்றும் நிதி','',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மற்றவை','Others',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',35,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அறிவியல் நாவல்','Science Fiction',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இதிகாச / புராண நாவல்','Epic / Mythological Novel',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கற்பனை நாவல்','Fantasy / Fictional Novel',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குறுங்கதைகள்','Short Stories',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குறுநாவல்','Short Story Novel',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமூக நாவல்','Social novel',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சரித்திர / வரலாற்று நாவல்','Historical Novel',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சிறுகதைகள்','Short Stories',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'திகில் நாவல்','Horror Novel',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'துப்பறியும் புதினம்','Detective Novel',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நகைச்சுவை','Comedy',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நாட்டுப்புறக் கதைகள்','NULL',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நெடுங்கதைகள்','Long Stories',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',36,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பொது அறிவு','General Knowledge',37,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பொன்மொழி','',38,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அனுபவம்','Experience',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஆன்மீகம் / பக்தி','Spritual',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இந்து மதம்','',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இஸ்லாமியம்','Islamiyam',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கவிதைகள்','Literature',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கிறித்துவம்','Christ',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமண மதம்','',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சமயக் கற்கைகள்','',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சீக்கியம்','Sikh',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சோதிடம்','',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நெறிமுறை','',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பஞ்சாங்கம்','',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'புத்தம் / பௌத்தம் / பவுத்தம்','',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மதம் / மதங்கள்','NULL',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'யூதம்','',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',39,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அக்குபிரஷர்','NULL',40,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'அலோபதி','NULL',40,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஆயுர்வேத மருத்துவம்','NULL',40,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இயற்கை மருத்துவம்','NULL',40,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கை வைத்தியம்','NULL',40,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சித்த வைத்தியம்','NULL',40,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நாட்டு வைத்தியம்','NULL',40,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பாட்டி வைத்தியம்','NULL',40,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மூலிகை வைத்தியம்','NULL',40,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஹோமியோபதி','Homeopathy',40,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இதழியல்','',41,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இலக்கணம்','',41,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'எழுதுதல் வழிகாட்டிகள்','',41,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கலை மற்றும் பேச்சுத்','',41,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழி','',41,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழி கற்றல் & போதனை','',41,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழியியல்','',41,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','',41,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'தாலாட்டுப் பாடல்கள்','',42,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நாட்டுப்புறக் கதைகள்','',42,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நாட்டுப்புறவியல்','',42,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கைத்தொழில் மற்றும் வணிக பிரிவுகள்','Industries & Business Sectors',43,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பொருளியல்','Economics',43,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வணிக சுய உதவி','Business Self-Help',43,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வணிகம், வியூகம் மற்றும் மேலாண்மை','Business, Strategy & Management',43,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வரலாறு','History',44,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வரலாற்று ஆய்வு','NULL',44,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நாட்குறிப்பு / நினைவுக்குறிப்பு','',44,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வரலாற்று கற்பனை','Historical Fiction',44,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வரலாற்றுச் சுவடு','NULL',44,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'வாழ்க்கை வரலாறு','NULL',44,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',44,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'விடுகதை','',45,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஏர் விளையாட்டு','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கபடி','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'காம்பாட் விளையாட்டு மற்றும் சுய பாதுகாப்பு','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கால்பந்து','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கால்ப்','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கிரிக்கெட்','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குதிரையேற்றம் மற்றும் விலங்கு விளையாட்டு','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'குளிர் கால விளையாட்டுக்கள்','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கூடைப்பந்து','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'சைக்கிள் ஓட்டுதல்','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'டிரையத்லான்','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'டென்னிஸ்','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நீர் விளையாட்டு','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பயிற்சி','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பாடிபில்டிங் மற்றும் பளு தூக்குதல்','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பூல், பில்லியர்ட்ஸ் மற்றும் ஸ்னூக்கர்','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'பேஸ்பால்','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மராத்தான் மற்றும் இயக்குதல்','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மோட்டார் விளையாட்டு','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ரக்பி','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'விளையாட்டு நிகழ்வுகள் மற்றும் நிறுவனங்கள்','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஜிம்னாஸ்டிக்ஸ்','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஸ்கேட்போர்டிங்','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மற்றவை','',46,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'இயற்கை விவசாயம்','',47,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'கட்டுரைகள்','',47,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'விவசாயம் / உழவு','',47,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'மொழிபெயர்ப்பு','Translation',47,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'ஓவியம் / ஓவியர்கள்','',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'எழுத்தாளர்கள் & படைப்புகள்','',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'புத்தகம்: முன்னுரைகள் / விமர்சனங்கள்','NULL',13,0,'A')
insert into dbo.Category(Category,Name,ParentID,IsShownInMenu,RecStatus)values(N'நாட்டாரியல்','NULL',13,0,'A')

